#!/usr/bin/env bash
# Bake hardened sshd defaults into the base image via a drop-in fragment.
# Modifying /etc/ssh/sshd_config directly fights apt upgrades; the drop-in
# under /etc/ssh/sshd_config.d/ overrides cleanly and survives unattended
# package upgrades on Ubuntu 22.04+.

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

# Ubuntu jammy ships /etc/ssh/sshd_config with `Include /etc/ssh/sshd_config.d/*.conf`
# at the top — verify before writing, fail loudly if the OS changed shape.
if ! grep -qE '^\s*Include\s+/etc/ssh/sshd_config\.d/\*\.conf' /etc/ssh/sshd_config; then
  echo "ERROR: /etc/ssh/sshd_config has no Include directive for sshd_config.d/*.conf" >&2
  echo "       Drop-in approach won't apply. Aborting." >&2
  exit 1
fi

install -d -m 0755 /etc/ssh/sshd_config.d

# Drop-in fragment. The `00-` prefix wins over any later snippet alphabetically,
# but sshd uses *first match wins* for most directives — so this file's settings
# take precedence over /etc/ssh/sshd_config defaults.
cat >/etc/ssh/sshd_config.d/00-sabokit-hardening.conf <<'EOF'
# Sabokit hardened sshd defaults. Drop-in baked at packer build time.
# Override per-host by adding a higher-numbered file under
# /etc/ssh/sshd_config.d/ — first match wins.

# Auth surface
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM yes
MaxAuthTries 3
MaxSessions 4
LoginGraceTime 30

# Forwarding: allow local (ansible tunnels DB ports etc.) but not remote/X11/agent.
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding local

# Session liveness
ClientAliveInterval 300
ClientAliveCountMax 2

# Banner / protocol
Protocol 2
Banner none

# Modern crypto — Mozilla "modern" OpenSSH profile, trimmed to algorithms
# present in OpenSSH 8.9 (Ubuntu jammy).
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com
EOF
chmod 0644 /etc/ssh/sshd_config.d/00-sabokit-hardening.conf

# Remove weak host keys if the upstream cloud image left any behind. On Ubuntu
# cloud images the keys are regenerated by the ssh-keygen systemd unit on first
# boot anyway (the cloud-init-cleaned image has no host keys), so this is
# belt-and-suspenders for any source image that pre-shipped them.
rm -f /etc/ssh/ssh_host_dsa_key /etc/ssh/ssh_host_dsa_key.pub
rm -f /etc/ssh/ssh_host_ecdsa_key /etc/ssh/ssh_host_ecdsa_key.pub

# Validate the merged config. `sshd -t` parses every Include'd file and exits
# non-zero on any syntax / unsupported-algorithm error — fail the build here
# instead of shipping a broken image.
sshd -t -f /etc/ssh/sshd_config

# Intentionally NOT restarting sshd: we're connected to the build VM over SSH
# right now, a restart would terminate the provisioner. The new config takes
# effect on first boot of any host cloned from this image (cloud-init starts
# sshd fresh). 99-cleanup.sh runs after this and doesn't touch ssh.
