#!/usr/bin/env python3
"""
Regenerate platform/ansible/apps.yml from every bundle's terraform outputs.tf.

For each bundle declared in BUNDLES below, this script:
  1. Parses platform/apps/<dir>/terraform/outputs.tf for the `vars = { ... }`
     block inside the `output "ansible" { ... }` stanza.
  2. Emits a YAML `- import_playbook:` block that explicitly maps every
     terraform-rendered var into the role namespace + adds <slug>_host_group.

Ansible's `import_playbook` requires a static dict for `vars:`, so the
verbose explicit form is the only correct shape — we can't expand a dict
expression dynamically. This generator owns that boilerplate so adding a
new bundle is one edit (the BUNDLES list) instead of N hand-written YAML
keys per bundle that drift the moment someone changes outputs.tf.

Usage:
  python3 scripts/gen_apps_yml.py            # write platform/ansible/apps.yml
  python3 scripts/gen_apps_yml.py --check    # exit 1 if file is stale (CI)

The CI workflow at .github/workflows/autogen.yml runs without --check on
every branch push and auto-commits regenerated files.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Entries: (bundle dir, consumer-template module key, role var prefix)
# - dir is the kebab-case bundle name on disk
# - key matches the entry in consumer-template/modules/stack/outputs.tf
#   `enabled_apps`. Differs from dir only for multi-instance bundles where
#   the example instance uses a suffix (e.g. backrest_mgmt).
# - role-slug is the underscored prefix used in each role's defaults/vars.
BUNDLES = [
    # (dir, consumer-key, role-slug)
    ("outline",        "outline",         "outline"),
    ("steward",        "steward",         "steward"),
    ("vikunja",        "vikunja",         "vikunja"),
    ("bentopdf",       "bentopdf",        "bentopdf"),
    ("notifuse",       "notifuse",        "notifuse"),
    ("privacy-policy", "privacy_policy",  "privacy_policy"),
    ("nextcloud",      "nextcloud",       "nextcloud"),
    ("decidim",        "decidim",         "decidim"),
    ("jitsi",          "jitsi",           "jitsi"),
    ("espocrm",        "espocrm",         "espocrm"),
    ("n8n",            "n8n",             "n8n"),
    ("backrest",       "backrest_mgmt",   "backrest"),
    ("prometheus",     "prometheus",      "prometheus"),
    ("loki",           "loki",            "loki"),
    ("grafana",        "grafana",         "grafana"),
    ("watchtower",     "watchtower_apps", "watchtower"),
    ("autoheal",       "autoheal_apps",   "autoheal"),
]

OUTPUT_PATH = REPO_ROOT / "platform/ansible/apps.yml"

HEADER = """---
# AUTO-GENERATED by scripts/gen_apps_yml.py. Do not edit by hand.
# Adding a bundle: append to BUNDLES in the generator, then re-run it.
#
# Deploy every enabled app. Apps assume the bootstrap roles are already on
# the host (Docker, Traefik, scw-secrets). Each app's role asserts its
# prereqs at the top of tasks/main.yml — failures here mean bootstrap was
# skipped or something got removed.
#
# Each import is conditional on `enabled_apps.<key>` being non-null. That
# map is produced by `terraform output -json enabled_apps` in the per-env
# deploy.sh and passed via `-e @enabled_apps.json`. Apps the consumer
# didn't enable evaluate to null and the import is skipped.
#
# Vars are spelled out per app — Ansible's `import_playbook` requires a
# static dict, so we explicitly map each terraform-rendered var into the
# role namespace.
"""


def extract_ansible_vars(outputs_tf: Path) -> list[str]:
    """Return the list of var names declared inside the `vars = { ... }`
    block of `output "ansible" { ... }` in the given outputs.tf."""
    text = outputs_tf.read_text()

    # Find the `output "ansible"` stanza first to avoid matching `vars = {`
    # inside other outputs (defensive — no app currently has that).
    m_output = re.search(
        r'output\s+"ansible"\s*\{(.*?)\n\}',
        text,
        flags=re.DOTALL,
    )
    if not m_output:
        return []
    stanza = m_output.group(1)

    # Find `vars = { ... }` within the stanza. Greedy until matching `}`
    # at the same indent.
    m_vars = re.search(
        r'vars\s*=\s*\{(.*?)\n\s*\}',
        stanza,
        flags=re.DOTALL,
    )
    if not m_vars:
        return []

    var_block = m_vars.group(1)

    # Each var line looks like "      foo_bar = ..." — capture the LHS.
    names = re.findall(
        r'^\s+([a-z][a-z0-9_]*)\s*=',
        var_block,
        flags=re.MULTILINE,
    )
    # Preserve order, drop duplicates if any (shouldn't be).
    seen: set[str] = set()
    ordered: list[str] = []
    for n in names:
        if n not in seen:
            seen.add(n)
            ordered.append(n)
    return ordered


def render_bundle(dir_name: str, consumer_key: str, role_slug: str,
                  vars: list[str]) -> str:
    """Render one import_playbook YAML block."""
    lines: list[str] = []
    lines.append(f"- import_playbook: ../apps/{dir_name}/ansible/playbook.yml")
    lines.append("  vars:")
    lines.append(
        f'    {role_slug}_host_group: '
        f'"{{{{ enabled_apps.{consumer_key}.ansible_group }}}}"'
    )
    for v in vars:
        lines.append(
            f'    {v}: '
            f'"{{{{ enabled_apps.{consumer_key}.ansible_vars.{v} }}}}"'
        )
    lines.append(
        f"  when: enabled_apps.{consumer_key} is defined "
        f"and enabled_apps.{consumer_key} is not none"
    )
    lines.append(f"  tags: [apps, {consumer_key}]")
    return "\n".join(lines) + "\n"


def generate() -> str:
    out = [HEADER]
    for dir_name, consumer_key, role_slug in BUNDLES:
        outputs_tf = REPO_ROOT / f"platform/apps/{dir_name}/terraform/outputs.tf"
        if not outputs_tf.exists():
            raise SystemExit(
                f"ERROR: {outputs_tf} not found (bundle dir mismatch?)"
            )
        vars = extract_ansible_vars(outputs_tf)
        if not vars:
            raise SystemExit(
                f"ERROR: no ansible.vars block found in {outputs_tf} — "
                "did the output shape change?"
            )
        out.append("")  # blank line between blocks
        out.append(render_bundle(dir_name, consumer_key, role_slug, vars))
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated content differs from the committed file.",
    )
    args = parser.parse_args()

    new = generate()
    if args.check:
        current = OUTPUT_PATH.read_text() if OUTPUT_PATH.exists() else ""
        if current != new:
            print(
                f"ERROR: {OUTPUT_PATH.relative_to(REPO_ROOT)} is stale. "
                "Run: python3 scripts/gen_apps_yml.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUTPUT_PATH.relative_to(REPO_ROOT)} up to date.")
        return 0

    OUTPUT_PATH.write_text(new)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(BUNDLES)} bundles).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
