#!/usr/bin/env python3
"""
Regenerate platform/ansible/apps.yml and platform/ansible/down.yml from every
bundle's terraform outputs.tf.

For each bundle declared in BUNDLES below, this script:
  1. Parses platform/apps/<dir>/terraform/outputs.tf for the `vars = { ... }`
     block inside the `output "ansible" { ... }` stanza.
  2. Emits a YAML `- import_playbook:` block (apps.yml) that explicitly maps
     every terraform-rendered var into the role namespace + adds
     <slug>_host_group.
  3. Emits a YAML teardown play (down.yml) tagged [down, <slug>] that runs
     community.docker.docker_compose_v2 state=absent against the role's
     install_dir. Volumes preserved by default; sabokit CLI --purge handles
     volume removal.

Ansible's `import_playbook` requires a static dict for `vars:`, so the
verbose explicit form is the only correct shape — we can't expand a dict
expression dynamically. This generator owns that boilerplate so adding a
new bundle is one edit (the BUNDLES list) instead of N hand-written YAML
keys per bundle that drift the moment someone changes outputs.tf.

Usage:
  python3 scripts/gen_apps_yml.py            # write apps.yml + down.yml
  python3 scripts/gen_apps_yml.py --check    # exit 1 if either is stale (CI)

The CI workflow at .github/workflows/autogen.yml runs without --check on
every branch push and auto-commits regenerated files.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Entries: (bundle dir, consumer-template module key, role var prefix)
# - dir is the kebab-case bundle name on disk
# - key matches the entry in consumer-template/modules/stack/outputs.tf
#   `enabled_apps`. Differs from dir only for multi-instance bundles where
#   the example instance uses a suffix (e.g. backrest_mgmt).
# - role-slug is the underscored prefix used in each role's defaults/vars.
# Bootstrap-tier bundles. Live under platform/bootstrap/ rather than
# platform/apps/ because they're host services apps depend on (inbound mail,
# etc.) rather than user-facing apps. Same import-playbook shape, different
# source directory.
BOOTSTRAP_BUNDLES = [
    # (dir, consumer-key, role-slug)
    ("protonmail-bridge", "protonmail_bridge", "protonmail_bridge"),
]

# Host-services bundles. Live under platform/base/host-services/ and are
# auto-instantiated per compute_host by platform/base/terraform/host_services.tf
# rather than hand-wired in consumer-template. The consumer-key is a template
# `<role-slug>_<host>` -- one entry per host the bundle's for_each produces --
# emitted by consumer-template/modules/stack/outputs.tf's enabled_apps merge.
# This generator emits one playbook-import block per host listed in
# HOST_SERVICE_HOSTS; the apps.yml when-guard skips disabled hosts.
HOST_SERVICE_HOSTS = ["apps", "management", "authentik"]

HOST_SERVICES_BUNDLES = [
    # (dir, role-slug)
    ("autoheal", "autoheal"),
]

BUNDLES = [
    # (dir, consumer-key, role-slug)
    ("outline",        "outline",         "outline"),
    ("steward",        "steward",         "steward"),
    ("vikunja",        "vikunja",         "vikunja"),
    ("bentopdf",       "bentopdf",        "bentopdf"),
    ("broadsheet",     "broadsheet",      "broadsheet"),
    ("privacy-policy", "privacy_policy",  "privacy_policy"),
    ("nextcloud",      "nextcloud",       "nextcloud"),
    ("decidim",        "decidim",         "decidim"),
    ("jitsi",          "jitsi",           "jitsi"),
    ("espocrm",        "espocrm",         "espocrm"),
    ("n8n",            "n8n",             "n8n"),
    ("backrest",       "backrest_mgmt",   "backrest"),
    ("prometheus",     "prometheus",      "prometheus"),
    ("loki",           "loki",            "loki"),
    ("grafana",        "grafana",         "grafana"),
    ("diun",           "diun_mgmt",       "diun"),
    ("wazuh",          "wazuh",           "wazuh"),
    ("wazuh-agent",    "wazuh_agent_apps","wazuh_agent"),
]

OUTPUT_PATH = REPO_ROOT / "platform/ansible/apps.yml"
DOWN_OUTPUT_PATH = REPO_ROOT / "platform/ansible/down.yml"
HOST_SERVICES_OUTPUT_PATH = REPO_ROOT / "platform/ansible/host-services.yml"

HEADER = """---
# AUTO-GENERATED by scripts/gen_apps_yml.py. Do not edit by hand.
# Adding a bundle: append to BUNDLES in the generator, then re-run it.
#
# Deploy every enabled app. Apps assume the bootstrap roles are already on
# the host (Docker, Traefik, scw-secrets). Each app's role asserts its
# prereqs at the top of tasks/main.yml — failures here mean bootstrap was
# skipped or something got removed.
#
# Each import is conditional on `enabled_apps.<key>` being non-null. That
# map is produced by `terraform output -json enabled_apps` in the per-env
# deploy.sh and passed via `-e @enabled_apps.json`. Apps the consumer
# didn't enable evaluate to null and the import is skipped.
#
# Vars are spelled out per app — Ansible's `import_playbook` requires a
# static dict, so we explicitly map each terraform-rendered var into the
# role namespace.
"""

DOWN_HEADER = """---
# AUTO-GENERATED by scripts/gen_apps_yml.py. Do not edit by hand.
# Adding a bundle: append to BUNDLES in the generator, then re-run it.
#
# Per-app teardown. One play per bundle, tagged [down, <app-slug>]. Stops
# and removes the app's compose stack via community.docker.docker_compose_v2
# (state: absent). Volumes are PRESERVED by default — the module's
# remove_volumes defaults to false. The sabokit CLI's --purge flag is
# responsible for volume removal.
#
# Each play loads the role defaults (for <slug>_install_dir etc.) via
# include_role with tasks_from=defaults, then runs compose-down. If a role
# ships its own tasks/down.yml, add an import_role line in this generator's
# render_down_bundle() — by convention, custom down hooks live there.
#
# Usage:
#   ansible-playbook down.yml -i env/inventory.ini -e @env/enabled_apps.json
#   ansible-playbook down.yml -i env/inventory.ini -e @env/enabled_apps.json --tags outline
"""


def extract_ansible_vars(outputs_tf: Path) -> list[str]:
    """Return the list of var names declared inside the `vars = { ... }`
    block of `output "ansible" { ... }` in the given outputs.tf."""
    text = outputs_tf.read_text()

    # Find the `output "ansible"` stanza first to avoid matching `vars = {`
    # inside other outputs (defensive — no app currently has that).
    m_output = re.search(
        r'output\s+"ansible"\s*\{(.*?)\n\}',
        text,
        flags=re.DOTALL,
    )
    if not m_output:
        return []
    stanza = m_output.group(1)

    # Find `vars = { ... }` within the stanza. Greedy until matching `}`
    # at the same indent.
    m_vars = re.search(
        r'vars\s*=\s*\{(.*?)\n\s*\}',
        stanza,
        flags=re.DOTALL,
    )
    if not m_vars:
        return []

    var_block = m_vars.group(1)

    # Each var line looks like "      foo_bar = ..." — capture the LHS.
    names = re.findall(
        r'^\s+([a-z][a-z0-9_]*)\s*=',
        var_block,
        flags=re.MULTILINE,
    )
    # Preserve order, drop duplicates if any (shouldn't be).
    seen: set[str] = set()
    ordered: list[str] = []
    for n in names:
        if n not in seen:
            seen.add(n)
            ordered.append(n)
    return ordered


def render_bundle(dir_name: str, consumer_key: str, role_slug: str,
                  vars: list[str], tier: str = "apps") -> str:
    """Render one import_playbook YAML block."""
    lines: list[str] = []
    lines.append(f"- import_playbook: ../{tier}/{dir_name}/ansible/playbook.yml")
    lines.append("  vars:")
    lines.append(
        f'    {role_slug}_host_group: '
        f'"{{{{ enabled_apps.{consumer_key}.ansible_group }}}}"'
    )
    for v in vars:
        lines.append(
            f'    {v}: '
            f'"{{{{ enabled_apps.{consumer_key}.ansible_vars.{v} }}}}"'
        )
    lines.append(
        f"  when: enabled_apps.{consumer_key} is defined "
        f"and enabled_apps.{consumer_key} is not none"
    )
    lines.append(f"  tags: [apps, {consumer_key}]")
    return "\n".join(lines) + "\n"


def render_down_bundle(dir_name: str, consumer_key: str,
                       role_slug: str, tier: str = "apps") -> str:
    """Render one teardown play. Targets `all` and scopes via tags + a
    per-task `when:` so the play parses even when an app isn't enabled.
    Loads role defaults so <slug>_install_dir is resolvable, then runs
    compose-down. Volumes preserved by default."""
    lines: list[str] = []
    lines.append(f'- name: "down: {dir_name}"')
    lines.append(
        f'  hosts: "{{{{ (enabled_apps.{consumer_key} | default({{}})).ansible_group '
        f"| default('all') }}}}\""
    )
    lines.append("  become: true")
    lines.append("  gather_facts: false")
    lines.append(f"  tags: [down, {consumer_key}]")
    lines.append("  tasks:")
    lines.append("    - name: Load role defaults")
    lines.append("      ansible.builtin.include_vars:")
    lines.append(
        f'        file: "../{tier}/{dir_name}/ansible/roles/{role_slug}/defaults/main.yml"'
    )
    lines.append(
        f"      when: enabled_apps.{consumer_key} is defined "
        f"and enabled_apps.{consumer_key} is not none"
    )
    lines.append("    - name: Stop and remove the compose stack")
    lines.append("      community.docker.docker_compose_v2:")
    lines.append(
        f'        project_src: "{{{{ {role_slug}_install_dir '
        f"| default('/opt/{dir_name}') }}}}\""
    )
    lines.append("        state: absent")
    lines.append(
        f"      when: enabled_apps.{consumer_key} is defined "
        f"and enabled_apps.{consumer_key} is not none"
    )
    lines.append("      ignore_errors: true  # compose file may already be gone")
    return "\n".join(lines) + "\n"


HOST_SERVICES_HEADER = """---
# AUTO-GENERATED by scripts/gen_apps_yml.py. Do not edit by hand.
# Adding a host-service bundle: append to HOST_SERVICES_BUNDLES in the
# generator, then re-run it.
#
# Per-host runtime watchers (autoheal, future diun + wazuh-agent). One
# import_playbook block per (bundle, host) pair. Each block is guarded by
# `enabled_apps.<slug>_<host>` being non-null -- the base layer's
# host_services for_each only produces an entry for hosts the consumer
# didn't disable, so disabled hosts evaluate to null and skip.
"""


def render_host_service_bundle(dir_name: str, role_slug: str,
                               host_key: str) -> str:
    consumer_key = f"{role_slug}_{host_key}"
    outputs_tf = REPO_ROOT / f"platform/base/host-services/{dir_name}/terraform/outputs.tf"
    vars = extract_ansible_vars(outputs_tf)
    if not vars:
        raise SystemExit(
            f"ERROR: no ansible.vars block found in {outputs_tf}."
        )
    lines: list[str] = []
    lines.append(
        f"- import_playbook: ../base/host-services/{dir_name}/ansible/playbook.yml"
    )
    lines.append("  vars:")
    lines.append(
        f'    {role_slug}_host_group: '
        f'"{{{{ enabled_apps.{consumer_key}.ansible_group }}}}"'
    )
    for v in vars:
        lines.append(
            f'    {v}: '
            f'"{{{{ enabled_apps.{consumer_key}.ansible_vars.{v} }}}}"'
        )
    lines.append(
        f"  when: enabled_apps.{consumer_key} is defined "
        f"and enabled_apps.{consumer_key} is not none"
    )
    lines.append(f"  tags: [host_services, {role_slug}, {consumer_key}]")
    return "\n".join(lines) + "\n"


def generate_host_services() -> str:
    out = [HOST_SERVICES_HEADER]
    for dir_name, role_slug in HOST_SERVICES_BUNDLES:
        for host_key in HOST_SERVICE_HOSTS:
            out.append("")
            out.append(render_host_service_bundle(dir_name, role_slug, host_key))
    return "".join(out)


def generate() -> str:
    out = [HEADER]
    for tier, bundles in (("bootstrap", BOOTSTRAP_BUNDLES), ("apps", BUNDLES)):
        for dir_name, consumer_key, role_slug in bundles:
            outputs_tf = REPO_ROOT / f"platform/{tier}/{dir_name}/terraform/outputs.tf"
            if not outputs_tf.exists():
                raise SystemExit(
                    f"ERROR: {outputs_tf} not found (bundle dir mismatch?)"
                )
            vars = extract_ansible_vars(outputs_tf)
            if not vars:
                raise SystemExit(
                    f"ERROR: no ansible.vars block found in {outputs_tf} — "
                    "did the output shape change?"
                )
            out.append("")  # blank line between blocks
            out.append(render_bundle(dir_name, consumer_key, role_slug, vars, tier))
    return "".join(out)


def generate_down() -> str:
    out = [DOWN_HEADER]
    for tier, bundles in (("bootstrap", BOOTSTRAP_BUNDLES), ("apps", BUNDLES)):
        for dir_name, consumer_key, role_slug in bundles:
            out.append("")  # blank line between plays
            out.append(render_down_bundle(dir_name, consumer_key, role_slug, tier))
    # Host-services teardown: one play per (bundle, host) pair, mirroring
    # the apps tier. Lives in down.yml so `sabokit destroy` reaches everything.
    for dir_name, role_slug in HOST_SERVICES_BUNDLES:
        for host_key in HOST_SERVICE_HOSTS:
            consumer_key = f"{role_slug}_{host_key}"
            out.append("")
            out.append(render_down_bundle(
                dir_name, consumer_key, role_slug, "base/host-services",
            ))
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated content differs from the committed file.",
    )
    args = parser.parse_args()

    new_apps = generate()
    new_down = generate_down()
    new_host_services = generate_host_services()

    if args.check:
        stale = False
        for path, new in (
            (OUTPUT_PATH, new_apps),
            (DOWN_OUTPUT_PATH, new_down),
            (HOST_SERVICES_OUTPUT_PATH, new_host_services),
        ):
            current = path.read_text() if path.exists() else ""
            if current != new:
                print(
                    f"ERROR: {path.relative_to(REPO_ROOT)} is stale. "
                    "Run: python3 scripts/gen_apps_yml.py",
                    file=sys.stderr,
                )
                stale = True
            else:
                print(f"OK: {path.relative_to(REPO_ROOT)} up to date.")
        return 1 if stale else 0

    OUTPUT_PATH.write_text(new_apps)
    DOWN_OUTPUT_PATH.write_text(new_down)
    HOST_SERVICES_OUTPUT_PATH.write_text(new_host_services)
    total = len(BUNDLES) + len(BOOTSTRAP_BUNDLES)
    host_total = len(HOST_SERVICES_BUNDLES) * len(HOST_SERVICE_HOSTS)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({total} bundles).")
    print(f"Wrote {DOWN_OUTPUT_PATH.relative_to(REPO_ROOT)} ({total + host_total} plays).")
    print(f"Wrote {HOST_SERVICES_OUTPUT_PATH.relative_to(REPO_ROOT)} ({host_total} plays).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
