---
- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    daemon_reload: true

- name: Restart Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_dir }}"
    restarted: true
  listen: "restart traefik"

- name: Reload Traefik
  community.docker.docker_container:
    name: "{{ traefik_container_name }}"
    restart: true
  listen: "reload traefik"
